//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cipher.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cipher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bronzeTexture {
            get {
                object obj = ResourceManager.GetObject("bronzeTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset0 Times New Roman;}{\f1\fnil\fcharset204 Times New Roman;}{\f2\froman\fcharset0 Times New Roman;}{\f3\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 10.0.17763}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs28\lang1033 Code-O-Graph\f1\lang1049\par
        ///
        ///\pard\b0\f0\fs22\lang1033 Code-O-Graph - \f1\lang1049\&apos;f8\&apos;e8\&apos;f4\&apos;f0\&apos;ee\&apos;e2\&apos;e0\&apos;eb\&apos;fc\&apos;ed\&apos;ee\&apos;e5 \&apos;f3\&apos;f1\&apos;f2\&apos;f0\&apos;ee\&apos;e9\&apos;f1\&apos;f2\&apos;e2\&apos;ee \&apos;e8\&apos; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Code_O_Graph {
            get {
                return ResourceManager.GetString("Code_O_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap metalTexture {
            get {
                object obj = ResourceManager.GetObject("metalTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paperTexture {
            get {
                object obj = ResourceManager.GetObject("paperTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodTexture {
            get {
                object obj = ResourceManager.GetObject("woodTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Times New Roman;}{\f1\fnil\fcharset0 Times New Roman;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.17763}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs28\lang1049\&apos;c4\&apos;e8\&apos;f1\&apos;ea \&apos;c0\&apos;eb\&apos;fc\&apos;e1\&apos;e5\&apos;f0\&apos;f2\&apos;e8\par
        ///
        ///\pard\sa200\sl240\slmult1\qc\b0\fs24{\pict{\*\picprop}\wmetafile8\picw6308\pich6244\picwgoal3576\pichgoal3540 
        ///0100090000038a04020000006104020000000400000003010800050000000b0200000000050000
        ///000c0227 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Диск_Альберти {
            get {
                return ResourceManager.GetString("Диск_Альберти", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1}.
        /// </summary>
        internal static string Диск_Г_Шотта {
            get {
                return ResourceManager.GetString("Диск_Г_Шотта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Times New Roman;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.17763}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs28\lang1049\&apos;d8\&apos;e8\&apos;f4\&apos;f0\&apos;e0\&apos;f2\&apos;ee\&apos;f0 \&apos;c2\&apos;ee\&apos;e4\&apos;f1\&apos;e2\&apos;ee\&apos;f0\&apos;e4\&apos;e0\par
        ///
        ///\pard\sa200\sl240\slmult1\qc\b0\fs24{\pict{\*\picprop}\wmetafile8\picw29189\pich22373\picwgoal8304\pichgoal6360 
        ///010009000003166321000000f762210000000400000003010800050000000c02dffb6305050000
        ///000b020000000005000000070104000000f [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Диск_Д_Водсворда {
            get {
                return ResourceManager.GetString("Диск_Д_Водсворда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Times New Roman;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.17763}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs28\lang1049\&apos;c4\&apos;e8\&apos;f1\&apos;ea\&apos;e8 \&apos;d7.\&apos;d3\&apos;e8\&apos;f2\&apos;f1\&apos;f2\&apos;ee\&apos;ed\&apos;e0 \&apos;e8 \&apos;cf\&apos;eb\&apos;e5\&apos;f2\&apos;f2\&apos;e0\par
        ///
        ///\pard\sa200\sl240\slmult1\b0\fs24{\pict{\*\picprop}\wmetafile8\picw26797\pich29337\picwgoal4308\pichgoal4752 
        ///01000900000316ba06000000edb9060000000400000003010800050000000b0200000000050000
        ///000c026a05f20403000 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Диски_Ч_Уитстона_и_Плетта {
            get {
                return ResourceManager.GetString("Диски_Ч_Уитстона_и_Плетта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1}.
        /// </summary>
        internal static string Устройство_Дж_Фонтана {
            get {
                return ResourceManager.GetString("Устройство_Дж_Фонтана", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1}.
        /// </summary>
        internal static string Шифратор_Ч_Бэббиджа {
            get {
                return ResourceManager.GetString("Шифратор_Ч_Бэббиджа", resourceCulture);
            }
        }
    }
}
