//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cipher.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cipher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bronzeTexture {
            get {
                object obj = ResourceManager.GetObject("bronzeTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap metalTexture {
            get {
                object obj = ResourceManager.GetObject("metalTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paperTexture {
            get {
                object obj = ResourceManager.GetObject("paperTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodTexture {
            get {
                object obj = ResourceManager.GetObject("woodTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Times New Roman;}{\f1\fnil\fcharset204 Calibri;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.17763}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs28\lang1049\&apos;c7\&apos;e0\&apos;e3\&apos;ee\&apos;eb\&apos;ee\&apos;e2\&apos;ee\&apos;ea\par
        ///
        ///\pard\sa200\sl276\slmult1\b0\f1\fs22\&apos;d2\&apos;e5\&apos;ea\&apos;f1\&apos;f2 \&apos;ed\&apos;ee\&apos;ec\&apos;e5\&apos;f0 1\f2\lang9\par
        ///}
        ///.
        /// </summary>
        internal static string Заголовок_1 {
            get {
                return ResourceManager.GetString("Заголовок_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Times New Roman;}{\f1\fnil\fcharset204 Calibri;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.17763}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs28\lang1049\&apos;c4\&apos;f0\&apos;f3\&apos;e3\&apos;ee\&apos;e9 \&apos;e7\&apos;e0\&apos;e3\&apos;ee\&apos;eb\&apos;ee\&apos;e2\&apos;ee\&apos;ea\par
        ///
        ///\pard\sa200\sl276\slmult1\b0\f1\fs22\&apos;d2\&apos;e5\&apos;ea\&apos;f1\&apos;f2 \&apos;ed\&apos;ee\&apos;ec\&apos;e5\&apos;f0 2\f2\lang9\par
        ///}
        ///.
        /// </summary>
        internal static string Заголовок_2 {
            get {
                return ResourceManager.GetString("Заголовок_2", resourceCulture);
            }
        }
    }
}
