//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cipher.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cipher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bronzeTexture {
            get {
                object obj = ResourceManager.GetObject("bronzeTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap metalTexture {
            get {
                object obj = ResourceManager.GetObject("metalTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paperTexture {
            get {
                object obj = ResourceManager.GetObject("paperTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodTexture {
            get {
                object obj = ResourceManager.GetObject("woodTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0{\fonttbl{\f0\fnil\fcharset204{\*\fname Arial;}Arial CYR;}{\f1\fnil\fcharset204{\*\fname Times New Roman;}Times New Roman CYR;}{\f2\fnil\fcharset0 Arial;}{\f3\fnil\fcharset0 Calibri;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\qc\lang1049\b\f0\fs28\&apos;c4\&apos;e0\&apos;f2\&apos;f1\&apos;ea\&apos;e8\&apos;e5 \&apos;f7\&apos;e0\&apos;f1\&apos;fb-\&apos;f8\&apos;e8\&apos;f4\&apos;f0\&apos;e0\&apos;f2\&apos;ee\&apos;f0\f1\par
        ///\pard\sa200\sl240\slmult1\qc\b0\fs24{\pict\wmetafile8\picw10583\pich11430\picwgoal6000\pichgoal6480 
        ///0100090000 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Датские_часы_шифратор {
            get {
                return ResourceManager.GetString("Датские_часы_шифратор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0{\fonttbl{\f0\fnil\fcharset204{\*\fname Arial;}Arial CYR;}{\f1\fnil\fcharset204{\*\fname Times New Roman;}Times New Roman CYR;}{\f2\fnil\fcharset0 Calibri;}{\f3\fnil\fcharset0 Arial;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\qc\lang1049\b\f0\fs28\&apos;c4\&apos;e8\&apos;f1\&apos;ea \&apos;c0.\&apos;cc\&apos;e0\&apos;e9\&apos;e5\&apos;f0\&apos;e0\f1\par
        ///\pard\sa200\sl240\slmult1\qc\lang9\b0\f2\fs22{\pict\wmetafile8\picw23204\pich26326\picwgoal8310\pichgoal9435 
        ///0100090000032cfb130000000dfb13000 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Диск_А_Майера {
            get {
                return ResourceManager.GetString("Диск_А_Майера", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0{\fonttbl{\f0\fnil\fcharset0 Arial;}{\f1\fnil\fcharset204{\*\fname Times New Roman;}Times New Roman CYR;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\qc\lang1033\b\fs28\u1044?\u1080?\u1089?\u1082? \u1040?\u1083?\u1100?\u1073?\u1077?\u1088?\u1090?\u1080?\lang1049\f1\par
        ///\pard\sa200\sl240\slmult1\qc\lang9\b0\f2\fs22{\pict\wmetafile8\picw6308\pich6244\picwgoal3576\pichgoal3540 
        ///0100090000038a0402000000610402000000040 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Диск_Альберти {
            get {
                return ResourceManager.GetString("Диск_Альберти", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0{\fonttbl{\f0\fnil\fcharset0 Arial;}{\f1\fnil\fcharset204{\*\fname Times New Roman;}Times New Roman CYR;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\qc\lang1033\b\fs28\u1044?\u1080?\u1089?\u1082? \u1041?\u1086?\u1083?\u1090?\u1086?\u1085?\u1072?\lang1049\f1\par
        ///\pard\sa200\sl240\slmult1\qc\lang9\b0\f2\fs22{\pict\wmetafile8\picw344\pich194\picwgoal6720\pichgoal6516 
        ///0100090000034d0c2000000029b10d000000161000002606 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Диск_Болтона {
            get {
                return ResourceManager.GetString("Диск_Болтона", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0{\fonttbl{\f0\fnil\fcharset0 Arial;}{\f1\fnil\fcharset204{\*\fname Times New Roman;}Times New Roman CYR;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\qc\lang1033\b\fs28\u1064?\u1080?\u1092?\u1088?\u1072?\u1090?\u1086?\u1088? \u1042?\u1086?\u1076?\u1089?\u1074?\u1086?\u1088?\u1076?\u1072?\lang1049\f1\par
        ///\pard\sa200\sl240\slmult1\qc\lang9\b0\f2\fs22{\pict\wmetafile8\picw29189\pich22373\picwgoal8304\pichgoal6360 
        ///01 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Диск_Д_Водсворда {
            get {
                return ResourceManager.GetString("Диск_Д_Водсворда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0{\fonttbl{\f0\fnil\fcharset0 Arial;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\qc\lang1033\b\fs28\u1044?\u1080?\u1089?\u1082?\u1080? \u1063?.\u1059?\u1080?\u1090?\u1089?\u1090?\u1086?\u1085?\u1072? \u1080? \u1055?\u1083?\u1077?\u1090?\u1090?\u1072?\par
        ///\pard\sa200\sl240\slmult1\lang9\b0\fs22{\pict\wmetafile8\picw26797\pich29337\picwgoal4308\pichgoal4752 
        ///01000900000316ba06000000edb9060000000400000003010800050000000b0200000000050000
        ///000c026 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Диски_Ч_Уитстона_и_Плетта {
            get {
                return ResourceManager.GetString("Диски_Ч_Уитстона_и_Плетта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fnil\fcharset0 Arial;}{\f1\fnil\fcharset0 Calibri;}{\f2\fnil\fcharset0 Courier New;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\qc\lang1033\fs28\u1052?\u1072?\u1096?\u1080?\u1085?\u1072? \u1092?\u1086?\u1085? \u1050?\u1088?\u1080?\u1093?\u1080?\fs22\par
        /// \par
        ///\pard\sl240\slmult1\lang9\f1{\pict\wmetafile8\picw15875\pich11906\picwgoal4005\pichgoal4305 
        ///010009000003482e06000000292e060000000400000003010800050000000c023efe5802050000
        ///000b0 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Машина_фон_Крихи {
            get {
                return ResourceManager.GetString("Машина_фон_Крихи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0{\fonttbl{\f0\fnil\fcharset0 Arial;}{\f1\fnil\fcharset204{\*\fname Arial;}Arial CYR;}{\f2\fnil\fcharset204{\*\fname Times New Roman;}Times New Roman CYR;}{\f3\fnil\fcharset0 Calibri;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\qc\lang1033\b\fs28\u1059?\u1089?\u1090?\u1088?\u1086?\u1081?\u1089?\u1090?\u1074?\u1086? \u1044?\u1078?.\u1060?\u1086?\u1085?\u1090?\u1072?\u1085?\lang1049\f1\&apos;fb\f2\par
        ///\pard\sa200\sl240\slmult1\qc\lang9\b0\f3\fs22{\pi [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Устройство_Дж_Фонтаны {
            get {
                return ResourceManager.GetString("Устройство_Дж_Фонтаны", resourceCulture);
            }
        }
    }
}
